"""Default documentation template for DevGuides."""

from typing import Dict, Any, Optional
from .base import MarkdownTemplate, HTMLTemplate

class DefaultMarkdownTemplate(MarkdownTemplate):
    """Default markdown template for general documentation."""
    
    def __init__(self):
        super().__init__(
            name="default",
            description="Default template for general-purpose documentation"
        )
    
    def format(
        self, 
        content: str, 
        mermaid_diagram: Optional[str],
        metadata: Dict[str, Any],
        output_format: str = "markdown"
    ) -> str:
        """Format content using the default template."""
        
        # Extract title from content
        title = self._extract_title(content)
        
        # Start building the result
        result = f"# {title}\n\n"
        
        # Add a brief intro
        result += f"*This documentation was generated in response to the query: \"{metadata.get('query', 'N/A')}\"*"
        result += f"\n\nGenerated on {self._get_timestamp()} using the {self.name} template.\n\n"
        
        # Add metadata section
        result += self.get_metadata_section(metadata)
        
        # Add main content
        result += content + "\n\n"
        
        # Add call flow diagram if available
        if mermaid_diagram:
            result += "## Call Flow Diagram\n\n"
            result += f"The following diagram shows the relationship between the key functions and components:\n\n"
            result += f"```mermaid\n{mermaid_diagram}\n```\n\n"
        
        # Add footer
        result += "---\n\n"
        result += "*This documentation was generated by DevGuides. "
        result += "For questions or issues, please refer to your codebase or DevGuides documentation.*"
        
        return result
    
    def _get_timestamp(self) -> str:
        """Get current timestamp."""
        import time
        return time.strftime('%Y-%m-%d %H:%M:%S')

class DefaultHTMLTemplate(HTMLTemplate):
    """Default HTML template for general documentation."""
    
    def __init__(self):
        super().__init__(
            name="default_html",
            description="Default template for general-purpose HTML documentation"
        )

class ConciseTemplate(MarkdownTemplate):
    """Template for concise documentation."""
    
    def __init__(self):
        super().__init__(
            name="concise",
            description="Template for concise, high-level documentation"
        )
    
    def format(
        self, 
        content: str, 
        mermaid_diagram: Optional[str],
        metadata: Dict[str, Any],
        output_format: str = "markdown"
    ) -> str:
        """Format content using the concise template."""
        
        title = self._extract_title(content)
        
        result = f"# {title}\n\n"
        result += f"*Brief overview generated for: \"{metadata.get('query', 'N/A')}\"*\n\n"
        
        # Add key metadata (minimal)
        key_info = []
        if "functions_analyzed" in metadata:
            key_info.append(f"Functions: {metadata['functions_analyzed']}")
        if "search_results_count" in metadata:
            key_info.append(f"Search results: {metadata['search_results_count']}")
        
        if key_info:
            result += f"*Key metrics: {' | '.join(key_info)}*\n\n"
        
        # Add condensed content (first few paragraphs only, excluding title)
        paragraphs = content.split('\n\n')
        # Skip the first paragraph if it's a title (starts with #)
        if paragraphs and paragraphs[0].strip().startswith('#'):
            content_paragraphs = paragraphs[1:4]  # Take next 3 paragraphs
        else:
            content_paragraphs = paragraphs[:3]  # Take first 3 paragraphs
        
        condensed_content = '\n\n'.join(content_paragraphs)
        
        result += condensed_content
        
        # Add simple diagram if available
        if mermaid_diagram:
            result += f"\n\n### Architecture Overview\n\n```mermaid\n{mermaid_diagram}\n```\n"
        
        return result

# Template registry
TEMPLATE_REGISTRY = {
    "default": DefaultMarkdownTemplate(),
    "default_html": DefaultHTMLTemplate(),
    "concise": ConciseTemplate(),
}

def get_template(template_name: str, output_format: str = "markdown"):
    """Get template by name and format."""
    
    # Handle format-specific template names
    if output_format == "html":
        template_key = f"{template_name}_html"
        if template_key in TEMPLATE_REGISTRY:
            return TEMPLATE_REGISTRY[template_key]
        # Fallback to HTML version of default template
        return TEMPLATE_REGISTRY["default_html"]
    
    # Return markdown template
    if template_name in TEMPLATE_REGISTRY:
        return TEMPLATE_REGISTRY[template_name]
    
    # Fallback to default template
    return TEMPLATE_REGISTRY["default"]

def list_templates():
    """List all available templates."""
    return {
        name: template.description 
        for name, template in TEMPLATE_REGISTRY.items()
    }